site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Connecting Razuna to a database :
  - Over view : 'db_connect/index.md'
  - MySQL : 'db_connect/MySQL.md'
  - Recommended MySQL settings : 'db_connect/Recommended MySQL settings.md'
  - MSSQL : 'db_connect/MSSQL.md'
  - Setup MSSQL Server for Razuna : 'db_connect/Setup MSSQL Server for Razuna.md'
  - DB2 : 'db_connect/DB2.md'
  - Oracle : 'db_connect/Oracle.md'
  - Run the Oracle Database scripts : 'db_connect/Run the Oracle Database scripts.md'
  - Migrate between databases : 'db_connect/Migrate databases.md'


