site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Install Guide:
  - Overview: 'installation/index.md'
  - Requirements: 'installation/requirement.md'
  - Linux: 'installation/linux.md'
  - Windows: 'installation/windows.md'
  - MacOs X: 'installation/macosx.md'
  - Razuna WAR Installation : 'installation/WAR.md'
  - Deploy on Virtual Machines: 'installation/vms.md'
  - Deploy on AWS (Amazon): 'installation/aws.md'
  - Use front-end server: 'installation/nginxapache.md'
  - Installing the Search Server : 'installation/Search_Server.md'
  - Installing a Razuna Rendering Server : 'installation/Render_Server.md'
  - Installation Trouble-Shooting : 'installation/Install_Trouble_Shoot.md'

