site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
pages: 
- Home : 'index.md'
- User Guide : 'user/index.md'
- Admin Guide : 'admin/index.md'
- API Guide : 'api/index.md'
- Installation Guide : 'installation/index.md'
- About : 'about/index.md'

