site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Gettin Started with Razuna:
  - Quick Start: 'start/quickstart.md'
  - Terminology: 'start/terminology.md'
  - Architecture: 'start/architecture.md'
- Install Guide:
  - Overview: 'installation/index.md'
  - Requirements: 'installation/requirement.md'
  - Linux: 'installation/linux.md'
  - Windows: 'installation/windows.md'
  - MacOs X: 'installation/macosx.md'
  - Razuna WAR Installation : 'installation/WAR.md'
  - Deploy on Virtual Machines: 'installation/vms.md'
  - Deploy on AWS (Amazon): 'installation/aws.md'
  - Use front-end server: 'installation/nginxapache.md'
  - Installing the Search Server : 'installation/Search_Server.md'
  - Installing a Razuna Rendering Server : 'installation/Render_Server.md'
  - Installation Trouble-Shooting : 'installation/Install_Trouble_Shoot.md'
  - Advanced Topics : 'installation/Advanced_Topic.md'
- Plugin Guide : 
  - Over view : 'plugins/index.md'
  - Plugin API : 'plugins/Plugin API.md'
  - Plugin Hooks : 'plugins/Plugin Hooks.md'
- Razuna FAQ :
  - Installation FAQ : 'Razuna_FAQ/index_installation_FAQ.md'
  - Adjusting Memory Settings for Tomcat : 'Razuna_FAQ/Adjust_memory.md'
  - Configure Tomcat for production deployment : 'Razuna_FAQ/Config_Tomcat.md'
  - How to move the asset directory to another drive : 'Razuna_FAQ/How_to_move_asset.md'
  - How to serve the DAM folder as its own web root : 'Razuna_FAQ/How_to_serve_DAM.md'
  - Monitoring Razuna (CF Server) with Nagios : 'Razuna_FAQ/Monitoring_Razuna.md'
  - Razuna with Apache 2.x as a front end server : 'Razuna_FAQ/Razuna_Apache2.md'
  - Razuna with Nginx as a front end server : 'Razuna_FAQ/Razuna_Nginx.md'
  - Running Razuna on a different port : 'Razuna_FAQ/Razuna_differ_port.md'
  - Single-Sign On Option : 'Razuna_FAQ/Single_Signon_option.md'
- Razuna Release Notes :
     - Over view : 'Release_Notes/index.md'
     - Razuna 1.7.5 : 'Release_Notes/Razuna 1.7.5.md'
     - Razuna 1.7 : 'Release_Notes/Razuna 1.7.md'
     - Razuna 1.6.5 : 'Release_Notes/Razuna 1.6.5.md'
     - Razuna 1.6.2 : 'Release_Notes/Razuna 1.6.2.md'
     - Razuna 1.6.1 : 'Release_Notes/Razuna 1.6.1.md'
     - Razuna 1.6 : 'Release_Notes/Razuna 1.6.md'
     - Razuna 1.5.2 : 'Release_Notes/Razuna 1.5.2.md'
     - Razuna 1.5.1 : 'Release_Notes/Razuna 1.5.1.md'
     - Razuna 1.5 : 'Release_Notes/Razuna 1.5.md'
     - Razuna 1.4.7 : 'Release_Notes/Razuna 1.4.7.md'
     - Razuna 1.4.6 : 'Release_Notes/Razuna 1.4.6.md'
     - Razuna 1.4.5 : 'Release_Notes/Razuna 1.4.5.md'
     - Razuna 1.4.4 : 'Release_Notes/Razuna 1.4.4.md'
     - Razuna 1.4.3 : 'Release_Notes/Razuna 1.4.3.md'
     - Razuna 1.4.2 : 'Release_Notes/Razuna 1.4.2.md'
     - Razuna 1.4.1 : 'Release_Notes/Razuna 1.4.1.md'
     - Razuna 1.4 : 'Release_Notes/Razuna 1.4.md'
- Developer Guide:
  - API Guide : 'api/index.md'
  - Plugin Guide : 'plugins/index.md'
  - API2 Guide : 
    - Over view : 'api/index.md'
    - Upload API2 : 'api/Upload API2.md'
    - Search API2 : 'api/Search API2.md'
    - Asset API2 : 'api/Asset API2.md'
    - Folder API2 : 'api/Folder API2.md'
    - Collection API2 : 'api/Collection API2.md'
    - Label API2 : 'api/Label API2.md'
    - Custom Fields API2 : 'api/Custom Fields API2.md'
    - User API2 : 'api/User API2.md'
    - Group API2 : 'api/Group API2.md'
    - Host API2 : 'api/Host API2.md'
    - Comment API2 : 'api/Comment API2.md'
    - Basket API2 : 'api/Basket API2.md'
  - API (old versions):
    - Over view : 'api old/index.md'
    - API Developer Guide version 1 : 'api old/API Guide ver1.md'
    - Authentication API1 : 'api old/Authentication API1.md'
    - Folder API1 : 'api old/Folder API1.md'
    - Collection API1 : 'api old/Collection API1.md'
    - Search API1 : 'api old/Search API1.md'
    - Upload API1 : 'api old/Upload API1.md'
    - Hosts API1 : 'api old/Hosts API1.md'
    - User API1 : 'api old/User API1.md'
    - Asset API1 : 'api old/Asset API1.md'
- About:
  - About: 'about/index.md'
  - License: 'about/license.md'
- Razuna Tools :
  - Over view : 'Razuna_tools/index.md'
  - Razuna Wordpress Plugin : 'Razuna_tools/Wordpress_plugin.md'
  - Razuna Chrome Extension : 'Razuna_tools/Chrome_Extension.md'
  - Razuna mobile optimised pages : 'Razuna_tools/Mobile_optimised.md'
  - Razuna Desktop : 'Razuna_tools/Razuna_desktop.md'
  - The Desktop File Restorer : 'Razuna_tools/Desktop_file_restorer.md'
  - Razuna Extension for Magento : 'Razuna_tools/Extension_for_Magento.md'
- User Guide : 'user/User Guide.md'
- Translation: 'Translation/Translation.md'
- Upgrade Razuna: 
   - Over view : 'Upgrade/index.md'
   - Upgrade from 1.3.5 to 1.4 : 'Upgrade/Upgrade from 135 to 14.md'
   - Upgrade from 1.2.3 to 1.3.5 : 'Upgrade/Upgrade from 123 to 135.md'
   - Upgrade from 1.2.3 to 1.3 : 'Upgrade/Upgrade from 123 to 13.md'
   - Upgrade from 1.2.2 to 1.2.3 : 'Upgrade/Upgrade from 122 to 123.md'
   - Upgrade from 1.2.1 to 1.2.2 : 'Upgrade/Upgrade from 121 to 122.md'
   - Upgrade from 1.2 to 1.2.1 : 'Upgrade/Upgrade from 12 to 121.md'
   - Upgrade from 1.1.4 to 1.2 : 'Upgrade/Upgrade from 114 to 12.md'
   - Upgrade from 1.1.3 to 1.1.4 : 'Upgrade/Upgrade from 113 to 114.md'
   