site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
 - API (old versions):
     - Over view : 'api old/index.md'
     - API Developer Guide version 1 : 'api old/API Guide ver1.md'
     - Authentication API1 : 'api old/Authentication API1.md'
     - Folder API1 : 'api old/Folder API1.md'
     - Collection API1 : 'api old/Collection API1.md'
     - Search API1 : 'api old/Search API1.md'
     - Upload API1 : 'api old/Upload API1.md'
     - Hosts API1 : 'api old/Hosts API1.md'
     - User API1 : 'api old/User API1.md'
     - Asset API1 : 'api old/Asset API1.md'


