site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Admin Backend Guide: 
  - Backup & Restore or migrate from one database to another : 'Admin_Backend/Backup_Restore.md'
  - Tenant Customization : 'Admin_Backend/Tenant_Customize.md'
  - Activate hosts with new settings : 'Admin_Backend/Activate_hosts.md'
  - Cloud Storage : 'Admin_Backend/Cloud_Storage.md'
  - Razuna Rendering Farm : 'Admin_Backend/Render_Farm.md'

