site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- How to show dedicated Razuna UI parts in your application : 'How/How_to_show_dedicated_Razuna_UI_parts.md'