site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Gettin Started with Razuna:
  - Quick Start: 'start/quickstart.md'
  - Terminology: 'start/terminology.md'
  - Architecture: 'start/architecture.md'
- Install Guide:
  - Overview: 'installation/index.md'
  - Requirements: 'installation/requirement.md'
  - Linux: 'installation/linux.md'
  - Windows: 'installation/windows.md'
  - MacOs X: 'installation/macosx.md'
  - Deploy on Virtual Machines: 'installation/vms.md'
  - Deploy on AWS (Amazon): 'installation/aws.md'
  - Upgrade Razuna: 'installation/upgrade.md'
- User Guide : 'user/index.md'
- Admin Guide : 'admin/index.md'
- Developer Guide:
  - API Guide : 'api/index.md'
  - Plugin Guide : 'plugins/index.md'
- About:
  - About: 'about/index.md'
  - License: 'about/license.md'


