site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Gettin Started with Razuna:
  - Quick Start: 'start/quickstart.md'
  - Terminology: 'start/terminology.md'
  - Architecture: 'start/architecture.md'
- Install Guide:
  - Overview: 'installation/index.md'
  - Requirements: 'installation/requirement.md'
  - Linux: 'installation/linux.md'
  - Windows: 'installation/windows.md'
  - MacOs X: 'installation/macosx.md'
  - Razuna WAR Installation : 'installation/WAR.md'
  - Deploy on Virtual Machines: 'installation/vms.md'
  - Deploy on AWS (Amazon): 'installation/aws.md'
  - Use front-end server: 'installation/nginxapache.md'
  - Installing the Search Server : 'installation/Search_Server.md'
  - Installing a Razuna Rendering Server : 'installation/Render_Server.md'
  - Installation Trouble-Shooting : 'installation/Install_Trouble_Shoot.md'
  - Advanced Topics : 'installation/Advanced_Topic.md'
- Plugin Guide : 
  - Over view : 'plugins/index.md'
  - Plugin API : 'plugins/Plugin API.md'
  - Plugin Hooks : 'plugins/Plugin Hooks.md'


  - The "My Folder": 'start/My Folder.md'
  - Batch Upload: 'start/Batch upload.md'
  - Search and Find Assets: 'start/Search_Find_Assets.md'
  - Link to existing content: 'start/Link_to_existing_content.md'
- Sharing Assets :
  - Over view : 'start/Sharing_assets.md'
  - Use Widgets: 'start/Use_Widget.md' 