site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Upgrade Razuna: 
   - Over view : 'Upgrade/index.md'
   - Upgrade from 1.3.5 to 1.4 : 'Upgrade/Upgrade from 135 to 14.md'
   - Upgrade from 1.2.3 to 1.3.5 : 'Upgrade/Upgrade from 123 to 135.md'
   - Upgrade from 1.2.3 to 1.3 : 'Upgrade/Upgrade from 123 to 13.md'
   - Upgrade from 1.2.2 to 1.2.3 : 'Upgrade/Upgrade from 122 to 123.md'
   - Upgrade from 1.2.1 to 1.2.2 : 'Upgrade/Upgrade from 121 to 122.md'
   - Upgrade from 1.2 to 1.2.1 : 'Upgrade/Upgrade from 12 to 121.md'
   - Upgrade from 1.1.4 to 1.2 : 'Upgrade/Upgrade from 114 to 12.md'
   - Upgrade from 1.1.3 to 1.1.4 : 'Upgrade/Upgrade from 113 to 114.md'