site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Gettin Started with Razuna:
  - Quick Start: 'start/quickstart.md'
  - Terminology: 'start/terminology.md'
  - Architecture: 'start/architecture.md'
  - The "My Folder": 'start/My Folder.md'
  - Batch Upload: 'start/Batch upload.md'
  - Search and Find Assets: 'start/Search_Find_Assets.md'
  - Link to existing content: 'start/Link_to_existing_content.md'
- Sharing Assets :
  - Use Widgets: 'start/Use_Widget.md' 