site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Admin Guide: 
  - Setting up Users : 'admin/users.md' 
  - Setting Groups :  'admin/groups.md'
  - Custom Fields : 'admin/custom fields.md'
  - Labels : 'admin/labels.md'
  - Scheduled Tasks : 'admin/Scheduled Tasks.md'
  - Rendition Templates : 'admin/Rendition templates.md'
  - Import Templates : 'admin/Import Templates.md'
  - Export Templates : 'admin/Export Templates.md'
  - Watermark Templates : 'admin/Watermark Templates.md'
  - Logs : 'admin/Logs.md'
  - Settings : 'admin/Settings.md'
  - Maintenance : 'admin/Maintenance.md'
  - Customization : 'admin/Customization.md'
  - Email Setup : 'admin/Email Setup.md'
  - Service Accounts : 'admin/Service Accounts.md'
  - Access Control : 'admin/Access Control.md'
  - Plugins : 'admin/Plugins.md'
  - LDAP Services : 'admin/LDAP Services.md'
  - White-Labelling : 'admin/White-Labelling.md'
  - Indexing : 'admin/Indexing.md'
  - Backup & Restore or migrate from one database to another : 'admin/backup_restore.md'
  - Razuna Rendering Farm : 'admin/Render_Farm.md'
  - Activate hosts with new settings : 'admin/Activate_hosts.md'
  - Tenant Customization : 'admin/Tenant_Customize.md'
  - Enable social network login : 'admin/Social_Login.md'
  - Cloud Storage : 'admin/Cloud_Storage.md'
  - Universal Product Code : 'admin/UPC.md'
