site_name: Razuna Documentation
theme: readthedocs
repo_url: https://github.com/razuna/razuna
repo_name: Github
markdown_extensions:
    - smarty
    - toc
pages: 
- Home : 'index.md'
- Razuna FAQ :
  - Installation FAQ : 'Razuna_FAQ/index_installation_FAQ.md'
  - Adjusting Memory Settings for Tomcat : 'Razuna_FAQ/Adjust_memory.md'
  - Configure Tomcat for production deployment : 'Razuna_FAQ/Config_Tomcat.md'
  - How to move the asset directory to another drive : 'Razuna_FAQ/How_to_move_asset.md'
  - How to serve the DAM folder as its own web root : 'Razuna_FAQ/How_to_serve_DAM.md'
  - Monitoring Razuna (CF Server) with Nagios : 'Razuna_FAQ/Monitoring_Razuna.md'
  - Razuna with Apache 2.x as a front end server : 'Razuna_FAQ/Razuna_Apache2.md'
  - Razuna with Nginx as a front end server : 'Razuna_FAQ/Razuna_Nginx.md'
  - Running Razuna on a different port : 'Razuna_FAQ/Razuna_differ_port.md'
  - Single-Sign On Option : 'Razuna_FAQ/Single_Signon_option.md'

- Oracle FAQ :
  - How to unlock the ORDSYS account : 'Razuna_FAQ/How_to_unlock_ORDSYS.md'